<form name="ThreeDForm" method="POST" action="<?php echo $block->getAuthUrl(); ?>">
    <button type="submit" class="action primary"><?php echo __('Continue') ?></button>
    <input type="hidden" name="PaReq" value="<?php echo $block->getAuthData(); ?>"/>
    <input type="hidden" name="TermUrl" value="<?php echo $block->getCallbackUrl(); ?>"/>
    <input type="hidden" name="MD" value="<?php echo $block->getRealOrderId(); ?>"/>
</form>
<script type="text/javascript">
    document.ThreeDForm.submit();
</script>
