<h3>3D Secure validation required. If your browser dont redirect you in 5 seconds. Press <?php echo __('Continue') ?></h3>
<form name="ThreeDForm" method="POST" action="<?php echo $block->getAuthUrl(); ?>">
    <button type="submit" class="action primary"><?php echo __('Continue') ?></button>
    <input type="hidden" name="PaReq" value="<?php echo $block->getAuthData(); ?>" />
    <input type="hidden" name="TermUrl" value="<?php echo $block->getCallbackUrl(); ?>" />
    <input type="hidden" name="MD" value="<?php echo $block->getMD(); ?>" />
</form>
<script type="text/javascript">
    window.onload = function() {
        window.setTimeout(document.ThreeDForm.submit.bind(document.ThreeDForm), 2000);
    };
</script>